---
# tasks file for tomcat-hac

- name: debug
  debug:
    msg: "{{ jdk_file }}"

- name: mkdir java tomcat
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/usr/local/java"
    - "/usr/local/tomcat"

- name: unarchive jdk
  unarchive:
    src: "{{ jdk_file }}"
    dest: /usr/local/java
    copy: yes

- name: unarchive tomcat
  unarchive:
    src: "{{ tomcat_file }}"
    dest: /usr/local/tomcat
    copy: yes

- name: config tomcat
  lineinfile:
    path: "{{ tomcat_path }}/bin/catalina.sh"
    insertafter: CATALINA_BASE=\"\$CATALINA_HOME\"
    line: CATALINA_PID="$CATALINA_BASE/tomcat.pid"
    firstmatch: yes

- name: tomcat service
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/tomcat.service

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: start tomcat
  systemd:
    name: tomcat
    state: restarted
    enabled: yes

- include: install_keepalived.yml

- include: install_nginx.yml
  when: keepalived.project == 'nginx'

- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /usr/local/nginx/conf/nginx.conf
  when: keepalived.project == 'nginx'

# 这一步非必须，只是为了看实验效果
- name: change jsp file
  lineinfile:
    path: "{{ tomcat_path }}/webapps/ROOT/index.jsp"
    regexp: '.*pageContext\.servletContext\.serverInfo.*$'
    firstmatch: yes
    line: '<h1>${pageContext.servletContext.serverInfo}({{ ansible_ens33.ipv4.address }})<%=request.getHeader("X-NGINX")%></h1>'
  when: keepalived.project == 'nginx'
  tags: debug

- name: copy keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes

- name: copy check script
  copy:
    src: "{{ keepalived.project }}_check.sh"
    dest: "{{ keepalived.script_path }}"
    mode: '0744'

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
