---
# vars file for mysql-hac

conn_port: 3306
conn_username: root
conn_password: $Zhou19961006
conn_socket: /var/lib/mysql/mysql.sock

mysql_users:
  - name: slave
    password: $Zhou19961006
    priv: '*.*:replication slave'
  - name: anban
    password: $Zhou19961006
    priv: "*.*:ALL"


keepalived:
  mysql_check: /etc/keepalived/mysql_check.sh
  vip: 10.0.0.100/24
  interface: ens33
  kill_keepalived: /etc/keepalived/kill_keepalived.sh
  project: 2

