---
- hosts: rhel7.5-test 
  vars:
    network_connections:
      - name: DBnic
        state: up
        type: ethernet
        interface_name: ens37 
        autoconnect: yes
        ip:
          dhcp4: yes
          auto6: no
  roles:
    - role: rhel-system-roles.network
